services:
  # Runs program inside a docker container. Not used in Jenkins.
  rad:
    platform: linux/amd64
    image: libera-rad:latest
    build:
      context: .
      target: libera-rad

  # Runs tests inside a docker container.
  tests:
    image: libera-rad-test:latest
    build:
      context: .
      target: libera-rad-test

  # Runs ruff in a docker container to check code style and formatting.
  # configuration file.
  linting:
    image: libera-rad-test:latest
    build:
      context: .
      target: libera-rad-test
    entrypoint: ["ruff", "check"]
